server:
  port: 9999
  
spring:
  application.name: springcloudgateway
  cloud:
    gateway:
      routes:
      - id: resouces01
        uri: http://localhost:8090
        predicates:
        - Path=/first/**
        filters:
        - SetPath=/
      - id: resouces02
        uri: http://localhost:8091
        predicates:
        - Path=/second/**
        filters:
        - SetPath=/